# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
require 'simplecov'
SimpleCov.start 'rails'
SimpleCov.coverage_dir 'coverage/cucumber'

require 'cucumber/rails'
require 'pry'
require 'cucumber/rspec/doubles'
require 'database_cleaner'

require Rails.root.join('lib', 'import')

ActionController::Base.allow_rescue = false

DatabaseCleaner.strategy = :transaction

Cucumber::Rails::Database.javascript_strategy = :truncation, {:except=>%w[spatial_ref_sys]} 

Before do
  DatabaseCleaner.start
end

After do
  DatabaseCleaner.clean
end

